name: tony.com
favicon: null
layout_spectrum: 0.02047514053992927
typography_spectrum: 0.17508498765528202
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6862458542454988
  lightness: 0.8385374904610217
  saturation: 0.9116263324394822
  rhythmicContrast: 0.7590106287971139
purpose: []
